# Generated by Django 5.0.6 on 2025-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("intensity", models.IntegerField()),
                ("sector", models.CharField(blank=True, max_length=255, null=True)),
                ("topic", models.CharField(max_length=255)),
                ("insight", models.TextField()),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("relevance", models.IntegerField()),
                ("pestle", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("likelihood", models.IntegerField()),
            ],
        ),
    ]
