# Generated by Django 5.0.6 on 2025-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataentry",
            name="intensity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="dataentry",
            name="likelihood",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dataentry",
            name="relevance",
            field=models.IntegerField(default=0),
        ),
    ]
